name: Build Documentation

on:
  push:
    branches:
      #- main
      - doc_net7
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Get dotnet sdk
      run: |
        wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        rm packages-microsoft-prod.deb
        sudo apt-get update
        #sudo apt remove dotnet-sdk-7.0 dotnet-runtime-7.0
        #sudo apt-get install -y dotnet-sdk-6.0 dotnet-runtime-6.0 
        sudo apt-get install -y dotnet-sdk-7.0 dotnet-runtime-7.0
    - name: Get docfx
      run: |
        dotnet tool update -g docfx
    - name: Install dependencies
      run: |
        dotnet restore
    - name: Build docs
      run:  |
        docfx Documentation/docfx.json build

    # - name: Deploy docfx documentation
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: Documentation/_site
