name: Release 2

permissions:
  contents: write

on:
  push:
    tags:
      - '**'

jobs:
  release2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - run: npx @aneoconsultingfr/order-github-release-notes
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
