name: Release 2

permissions:
  contents: write

on:
  push:
    tags:
      - '**'

jobs:
  release2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: 16.x

      - run: npx @aneoconsultingfr/order-github-release-notes
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
